version: '2'

services:
  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761

  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8888:8888

  zuul-apigateway:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
      - music-service
      - user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080
